apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-deploy-history
  namespace: default
data:
  history.jsonl: "{\"build_number\":\"9\",\"git_commit\":\"4c9c850\",\"status\":\"success\",\"timestamp\":\"2026-07-31T06:29:53Z\"}\n{\"build_number\":\"8\",\"git_commit\":\"1357f7e\",\"status\":\"success\",\"timestamp\":\"2026-07-31T05:34:30Z\"}\n{\"build_number\":\"7\",\"git_commit\":\"32c6204\",\"status\":\"success\",\"timestamp\":\"2026-07-31T05:21:55Z\"}\n{\"build_number\":\"6\",\"git_commit\":\"9fbf042\",\"status\":\"success\",\"timestamp\":\"2026-07-31T05:14:16Z\"}\n{\"build_number\":\"5\",\"git_commit\":\"644b894\",\"status\":\"success\",\"timestamp\":\"2026-07-31T05:08:38Z\"}\n{\"build_number\":\"4\",\"git_commit\":\"c01e4b8\",\"status\":\"rollback\",\"recovered_build\":\"\",\"timestamp\":\"2026-07-31T04:58:45Z\"}"
